test:uipath-langchain:
  - changed-files:
    - any-glob-to-any-file: ['src/**/*.py']

test:uipath-runtime:
  - changed-files:
    - any-glob-to-any-file: ['src/**/*.py']

test:uipath:
  - changed-files:
    - any-glob-to-any-file: ['src/**/*.py']
